services:
  - type: web
    name: spa-de-eliz
    env: python
    rootDir: backend   # 👈 carpeta donde está app.py y requirements.txt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
